version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: emailservice-backend
    restart: unless-stopped
    depends_on:
      - minio
    environment:
      PORT: 4000

      # Mongo
      MONGO_URI: mongodb://mongodb:27017
      MONGO_DB_NAME: placement_erp

      # Redis
      REDIS_URL: redis://redis:6379

      # Kafka
      KAFKA_CLIENT_ID: placement-approval-service
      KAFKA_BROKERS: redpanda:9092
      KAFKA_CONSUMER_GROUP: placement-approval-group
      KAFKA_PENDING_TOPIC: job.notification.pending
      KAFKA_SEND_TOPIC: job.notification.send

      # MinIO
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: email-bodies

    ports:
      - "${BACKEND_HOST_PORT:-4400}:4000"

    networks:
      - erp-core-net
      - redis-core-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL:-http://134.209.159.132:4400}
    container_name: emailservice-frontend
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      VITE_API_URL: ${VITE_API_URL:-http://134.209.159.132:4400}
      PORT: 3000
    ports:
      - "${FRONTEND_HOST_PORT:-3300}:3000"
    networks:
      - erp-core-net
      - redis-core-network

  email-consumer:
    build:
      context: ./email-consumer
      dockerfile: Dockerfile
    container_name: emailservice-email-consumer
    restart: unless-stopped
    depends_on:
      - minio
    environment:
      # Kafka
      KAFKA_CLIENT_ID: email-consumer
      KAFKA_BROKERS: redpanda:9092
      KAFKA_CONSUMER_GROUP: email-consumer-group
      KAFKA_SEND_TOPIC: job.notification.send

      # MinIO
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: email-bodies

      # ZeptoMail (Zoho)
      ZEPTOMAIL_API_URL: https://api.zeptomail.in/v1.1/email
      ZEPTOMAIL_TOKEN: Zoho-enczapikey PHtE6r0LF+nsj2Yv+0ACt/K/EMb3NYoprOgyKAlOtYhEC6BRHU0BqNoixDCy+kgoA6FCEPHJyI0+s7+V57qAJ2ruZmZLXGqyqK3sx/VYSPOZsbq6x00at1weckXYVo7td9Jp0yTTstmX
      FROM_EMAIL: "noreply@sumantheluri.tech"
      FROM_NAME: Placement Cell

    networks:
      - erp-core-net
      - redis-core-network

  minio:
    image: minio/minio:latest
    container_name: emailservice-minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - minio-data:/data
    networks:
      - erp-core-net
      - redis-core-network

volumes:
  minio-data:


networks:
  erp-core-net:
    external: true
    name: erp-core-net

  redis-core-network:
    external: true
    name: redis-core-network
